language: python
virtualenv:
  system_site_packages: true
python:
 - "3.4"
 - "3.5"
 - "3.6"

install:
 - pip install -r dev-requirements.txt
 - pip install -r requirements.txt
 - pip install .

scripts:
 - pytest -v
