
env:
  matrix:
    - WASP_ENABLE_CHECKS=
    - WASP_ENABLE_CHECKS=*
    - WASP_ENABLE_CHECKS=strict:paranoid

matrix:
  include:

# Python 3.4 ignored due to tornado requirement of python >= 3.4

    - python: "3.4"

    - python: "3.5"

    - python: "3.6"

    - dist: xenial
      python: "3.7"

    - dist: xenial
      python: "pypy3.5"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -v .

script:
  - cd tests
  - coverage run --source wasp_general -m py.test

after_script:
  - coveralls
