language: python

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

jobs:
  include:
    - stage: PEP8 tests
      python:
        - "3.6"

      script:
        - cd tests; py.test -c pytest-pep8.ini; cd ..

    - stage: Unit tests and coverage test
      python:
      # - "3.3" # ignored due to tornado requirement of python >= 3.4
        - "3.4"
        - "3.5"
        - "3.6"

      script:
        - coverage run --source wasp_general -m py.test tests/

      after_script:
        - coveralls
