
#env:
#  matrix:
#    - WASP_ENABLE_CHECKS=
#    - WASP_ENABLE_CHECKS=*
#    - WASP_ENABLE_CHECKS=strict:paranoid

language: python
#python:
# - "3.3" # ignored due to tornado requirement of python >= 3.4
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "pypy3.5"
#  - python: "3.9"
#    dist: bionic

matrix:
  include:
    - python: "3.9"
      dist: bionic
      
install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -v .

script:
  - cd tests
  - coverage run --source wasp_general -m py.test

#after_script:
#  - coveralls
